sudo: required
language: java
before_install:
  - mvn -v
  - apt-cache show maven
  - sudo apt-get -y maven=3.2.5
install: mvn install -DskipTests=true -Dgpg.skip=true
jdk:
  - openjdk6
  - oraclejdk8
services:
  - docker
before_script:
  - docker run -d -p 127.0.0.1:8123:8123 --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:1.1.54159
